name: action
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  figma_squircle: ^0.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints_y:
    git:
      url: https://github.com/Yogi-7y/Project-Y
      path: packages/lints
      ref: main

flutter:
  uses-material-design: true

  assets:
    - assets/heavy_plus.svg
